alert_threshold: 1
alert_window_min: 5
email:
  enabled: false
  password: ''
  smtp_host: smtp.gmail.com
  smtp_port: 587
  to: ''
  user: ''
poll_interval: 10
reset_hour: 0
symbols:
- BNB
- BTC
- VET
- VTHO
- ETH
telegram:
  bot_token: ''
  chat_id: ''
  enabled: false
